pr:
- master
- release/*

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    windows:
      imageName: "vs2017-win2016"
  maxParallel: 2

pool: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build in Release mode'